# 智能约束系统配置文件
# 通过字段名匹配来应用约束规则

# 保持原值不变的字段约束
# 适用于需要保持固定值的字段，如报文头部信息等
[Head]
type = "keep_original"
description = "保持Head节点及其所有子字段的原值不变"

[SvcCd]
type = "keep_original"
description = "保持服务代码原值不变"

[SvcScn]
type = "keep_original"
description = "保持服务场景原值不变"

# 日期字段约束
[date]
type = "date"
format = "20060102"  # Go时间格式
min_date = "20200101"
max_date = "20301231"
description = "日期字段，格式为YYYYMMDD"

[create_date]
type = "date"
format = "20060102"
min_date = "20200101"
max_date = "20301231"

[update_date]
type = "date"
format = "20060102"
min_date = "20200101"
max_date = "20301231"

# 姓名字段约束
[name]
type = "chinese_name"
description = "中文姓名"

[user_name]
type = "chinese_name"

[username]
type = "chinese_name"

[real_name]
type = "chinese_name"

# 年龄字段约束
[age]
type = "integer"
min = 1
max = 120
description = "年龄范围1-120"

# 手机号字段约束
[phone]
type = "phone"
description = "中国大陆手机号"

[mobile]
type = "phone"

[phone_number]
type = "phone"

# 邮箱字段约束
[email]
type = "email"
description = "邮箱地址"

[email_address]
type = "email"

# 价格字段约束
[price]
type = "float"
min = 0.01
max = 999999.99
precision = 2
description = "价格，保留2位小数"

[amount]
type = "float"
min = 0.01
max = 999999.99
precision = 2

[money]
type = "float"
min = 0.01
max = 999999.99
precision = 2

# 地址字段约束
[address]
type = "chinese_address"
description = "中文地址"

[addr]
type = "chinese_address"

[location]
type = "chinese_address"

# 身份证号字段约束
[id_card]
type = "id_card"
description = "中国身份证号"

[identity_card]
type = "id_card"

[card_no]
type = "id_card"

# 数量字段约束
[quantity]
type = "integer"
min = 1
max = 10000
description = "数量"

[qty]
type = "integer"
min = 1
max = 10000

[count]
type = "integer"
min = 1
max = 10000

# 状态字段约束
[status]
type = "integer"
min = 0
max = 9
description = "状态码"

# 编号字段约束
[id]
type = "integer"
min = 1
max = 999999
description = "ID编号"

[user_id]
type = "integer"
min = 1
max = 999999

[order_id]
type = "integer"
min = 1
max = 999999

# 内置数据集
[builtin_data]

# 中文姓名数据集
first_names = [
    "张", "王", "李", "赵", "刘", "陈", "杨", "黄", "周", "吴",
    "徐", "孙", "马", "朱", "胡", "林", "郭", "何", "高", "罗"
]

last_names = [
    "伟", "芳", "娜", "敏", "静", "丽", "强", "磊", "军", "洋",
    "勇", "艳", "杰", "涛", "明", "超", "秀英", "霞", "平", "刚",
    "桂英", "建华", "建国", "建军", "志强", "志明", "秀兰", "秀珍",
    "春梅", "桂兰", "玉兰", "玉梅", "玉华", "玉珍", "桂花", "桂珍",
    "丽娟", "丽华", "丽萍", "丽君", "海燕", "海霞", "海英", "海华",
    "亦菲", "晓明", "德华", "学友", "嘉欣", "志伟", "家辉", "国荣"
]

# 中文地址数据集
addresses = [
    "北京市朝阳区建国门外大街1号",
    "上海市浦东新区陆家嘴环路1000号",
    "广州市天河区珠江新城花城大道85号",
    "深圳市南山区科技园南区深南大道9988号",
    "杭州市西湖区文三路259号",
    "南京市鼓楼区中山路1号",
    "武汉市武昌区中南路99号",
    "成都市高新区天府大道中段1388号",
    "重庆市渝中区解放碑步行街88号",
    "西安市雁塔区高新四路15号",
    "天津市和平区南京路128号",
    "苏州市工业园区苏州大道东289号",
    "青岛市市南区香港中路76号",
    "大连市中山区人民路15号",
    "厦门市思明区湖滨南路76号"
]

# 邮箱域名数据集
email_domains = [
    "qq.com", "163.com", "126.com", "gmail.com", "sina.com",
    "sohu.com", "hotmail.com", "yahoo.com", "139.com", "189.cn"
]