# 测试保持原值不变功能的约束配置文件

# 保持Head节点及其所有子字段的原值不变
[Head]
type = "keep_original"
description = "保持Head节点及其所有子字段的原值不变"

# 对TxnDt字段单独设置约束，覆盖Head的keep_original设置
[TxnDt]
type = "date"
format = "20060102"
min_date = "20200101"
max_date = "20301231"
description = "交易日期，格式为YYYYMMDD"

# Body节点下的字段使用默认变化逻辑（不设置约束）
# IdentTp1, IdentNoS, TxnCnl, IntfDoctnVerNo 将会按照默认规则变化

# 可以为Body下的特定字段设置约束
[IdentNoS]
type = "id_card"
description = "身份证号"

# 内置数据集
[builtin_data]

# 中文姓名数据集
first_names = [
    "张", "王", "李", "赵", "刘", "陈", "杨", "黄", "周", "吴",
    "徐", "孙", "马", "朱", "胡", "林", "郭", "何", "高", "罗"
]

last_names = [
    "伟", "芳", "娜", "敏", "静", "丽", "强", "磊", "军", "洋",
    "勇", "艳", "杰", "涛", "明", "超", "秀英", "霞", "平", "刚"
]

# 中文地址数据集
addresses = [
    "北京市朝阳区建国门外大街1号",
    "上海市浦东新区陆家嘴环路1000号",
    "广州市天河区珠江新城花城大道85号",
    "深圳市南山区科技园南区深南大道9988号",
    "杭州市西湖区文三路259号"
]

# 邮箱域名数据集
email_domains = [
    "qq.com", "163.com", "126.com", "gmail.com", "sina.com"
]